force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>This object represents Photos records imported from external system.</description>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/Album_Id__c.field-meta.xml
<CustomField>
    <fullName>Album_Id__c</fullName>
    <description>Id of the album containing this photo</description>
    <label>Album Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id of the photo taken from the external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Thumbnail_Url__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_Url__c</fullName>
    <description>Url for photo thumbnail</description>
    <label>Thumbnail Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the photo</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Url location of the photo</description>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PhotoObjectUtilTest.cls
@IsTest
public with sharing class PhotoObjectUtilTest {

    @IsTest
    static void should_ReturnTrue_when_AllTrackedCustomFieldsAreEqual() {
        //given
        Photo__c photo1 = new PhotoTestHelper.PhotoBuilder().build();
        Photo__c photo2 = new PhotoTestHelper.PhotoBuilder().build();

        //when
        Test.startTest();
        Boolean arePhotosEqual = PhotoObjectUtil.areEqual(photo1, photo2);
        Test.stopTest();

        //then
        System.assert(arePhotosEqual, 'Expecting that photos are equal');
    }

    @IsTest
    static void should_ReturnFalse_when_TrackedCustomFieldsAreNotEqual() {
        //given
        Photo__c photo1 = new PhotoTestHelper.PhotoBuilder().build();
        Photo__c photo2 =  new PhotoTestHelper.PhotoBuilder().withExternalId('2').build();

        //when
        Test.startTest();
        Boolean arePhotosEqual = PhotoObjectUtil.areEqual(photo1, photo2);
        Test.stopTest();

        //then
        System.assert(!arePhotosEqual, 'Expecting that photos are not equal');
    }

    @IsTest
    static void should_Parse_JSONDataToPhoto() {
        //given
        String testFetchedData = PhotoTestHelper.EXAMPLE_RESPONSE_BODY_SINGLE_RECORD;
        Map<String, Object> fetchedRecordAsMap = 
            (Map<String,Object>)(((List<Object>)JSON.deserializeUntyped(testFetchedData))[0]);

        //when
        Test.startTest();
        Photo__c parsedPhoto = PhotoObjectUtil.parseExternalRecordToPhoto(fetchedRecordAsMap);
        Test.stopTest();

        //then
        System.assertEquals('1', parsedPhoto.Album_Id__c, 'Expecting specific value of parsed Photo Album Id');
        System.assertEquals('1', parsedPhoto.External_Id__c, 'Expecting specific value of parsed Photo External Id');
        System.assertEquals('accusamus beatae ad facilis cum similique qui sunt', parsedPhoto.Title__c, 
            'Expecting specific value of parsed Photo Title');
        System.assertEquals('https://via.placeholder.com/600/92c952', parsedPhoto.Url__c, 
            'Expecting specific value of parsed Photo Url');
        System.assertEquals('https://via.placeholder.com/150/92c952', parsedPhoto.Thumbnail_Url__c, 
            'Expecting specific value of parsed Photo Thumbnail Url');
    }
}