force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>This object represents Photos records imported from external system.</description>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id of the photo taken from the external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Thumbnail_Url__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_Url__c</fullName>
    <description>Url for photo thumbnail</description>
    <label>Thumbnail Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the photo</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Title_Trimmed__c.field-meta.xml
<CustomField>
    <fullName>Title_Trimmed__c</fullName>
    <description>Trimmed version of the title</description>
    <inlineHelpText>This field is populated automatically</inlineHelpText>
    <label>Title Trimmed</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhotoSearchController.cls
public with sharing class PhotoSearchController {

    @AuraEnabled(Cacheable=true)
    public static SearchResult getPhotos(SearchProperties searchProperties) {
        
        String key, whereClause = '';
        if (String.isNotBlank(searchProperties.searchKey)) {
            whereClause = 'WHERE Title__c LIKE  \'%' + searchProperties.searchKey + '%\'';
        }
        Integer pageSize = searchProperties.pageSize;
        Integer offset = (searchProperties.pageNumber - 1) * pageSize;
        
        SearchResult result = new SearchResult();
        result.pageSize = searchProperties.pageSize;
        result.pageNumber = searchProperties.pageNumber;

        result.totalItemCount = Database.countQuery(
            'SELECT COUNT() FROM Photo__c ' + whereClause
        );

        result.records = Database.query(
            'SELECT Id, Title_Trimmed__c, Thumbnail_Url__c, External_Id__c FROM Photo__c ' + whereClause + ' WITH SECURITY_ENFORCED ORDER BY External_Id__c LIMIT :pageSize OFFSET :offset'
        );
        return result;
    }

    @AuraEnabled
    public static void sendEmail(String toAddress, String body) {
        
        try{
            Messaging.reserveSingleEmailCapacity(1);
            messaging.SingleEmailMessage mail = new messaging.SingleEmailMessage();        
        
            mail.setToAddresses(new List<String>{toAddress});
            mail.setReplyTo(UserInfo.getUserEmail());
            mail.setSenderDisplayName(UserInfo.getUserName());
            mail.setSubject('Photo Gallery Search result - ' + Datetime.now());
            mail.setHtmlBody(body);
            Messaging.sendEmail(new List<messaging.SingleEmailMessage> {mail});
        }
        catch (exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    public with sharing class SearchProperties {
        @AuraEnabled
        public String searchKey { get; set; }
        @AuraEnabled
        public Integer pageSize { get; set; }
        @AuraEnabled
        public Integer pageNumber { get; set; }
    }
}