force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>This object represents Photos records imported from external system.</description>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/Photo_Data_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains mappings for fields used to synchronize Photo Data between external service and Salesforce. Only fields specified in this mapping will be synched.</description>
    <label>Photo Data Field Mapping</label>
    <pluralLabel>Photo Data Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/fields/External_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Field_Name__c</fullName>
    <description>This field contains name of the field to map from external system</description>
    <label>External Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <description>This field contains name of the field to map in Salesforce</description>
    <inlineHelpText>Please put the API name here (with __c appendix)</inlineHelpText>
    <label>Salesforce Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PhotoObjectUtil.cls
/**
 * This class contains util methods for working with Photo__c object
 */
public with sharing class PhotoObjectUtil {
    
    /**
     * This method will compare two records by comparing their properties which are 
     * synchronized between external system and Salesforce
     */
    public static Boolean areEqual(Photo__c firstPhoto, Photo__c secondPhoto) {

        for(Photo_Data_Field_Mapping__mdt pdfm : CustomMetadataSelector.getPhotoDataFieldMappingMetadata()) {
            if(firstPhoto.get(pdfm.Salesforce_Field_Name__c) != secondPhoto.get(pdfm.Salesforce_Field_Name__c)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method will return Photo__c object basing on the records fetched from the external system.able 
     * All fields from Custom Metadata mapping will be parsed to SObject
     */
    public static Photo__c parseExternalRecordToPhoto(Map<String, Object> externalRecord) {
        Photo__c parsedPhoto = new Photo__c();
        for(Photo_Data_Field_Mapping__mdt pdfm : CustomMetadataSelector.getPhotoDataFieldMappingMetadata()) {
            parsedPhoto.put(
                pdfm.Salesforce_Field_Name__c, String.valueOf(externalRecord.get(pdfm.External_Field_Name__c)));
        }
        return parsedPhoto;
    }
}