force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <description>This object represents Photos records imported from external system.</description>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/Album_Id__c.field-meta.xml
<CustomField>
    <fullName>Album_Id__c</fullName>
    <description>Id of the album containing this photo</description>
    <label>Album Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id of the photo taken from the external system</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Thumbnail_Url__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_Url__c</fullName>
    <description>Url for photo thumbnail</description>
    <label>Thumbnail Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the photo</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Url location of the photo</description>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PhotoTestHelper.cls
/**
 * Helper class for tests related with Photo object
 */
public with sharing class PhotoTestHelper {

    public static final String TEST_ID = '1';
    public static final String TEST_ALBUM_ID = '1';
    public static final String TEST_THUMBNAIL_URL = 'https://via.placeholder.com/150/1fe46f';
    public static final String TEST_TITLE = 'laboriosam odit nam necessitatibus et illum dolores reiciendis';
    public static final String TEST_URL = 'https://via.placeholder.com/600/1fe46f';

    /**
     * Builder for Photo__c SObject
     */
    public class PhotoBuilder {
        private Photo__c record;

        public PhotoBuilder() {
            reset();
        }

        private Photo__c getDefaultRecord() {
            Photo__c defaultPhoto = new Photo__c();
            defaultPhoto.External_Id__c =  TEST_ID;
            defaultPhoto.Album_Id__c = TEST_ALBUM_ID;
            defaultPhoto.Thumbnail_Url__c = TEST_THUMBNAIL_URL;
            defaultPhoto.Title__c = TEST_TITLE;
            defaultPhoto.Url__c = TEST_URL;
            return defaultPhoto;
        }

        public PhotoBuilder reset() {
            record = getDefaultRecord();
            return this;
        }

        public PhotoBuilder withExternalId(String externalId) {
            record.External_Id__c = externalId;
            return this;
        }

        public Photo__c build() {
            return record;
        }

        public Photo__c buildAndSave() {
            upsert record;
            return record;
        }
    }
}