force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/Photo_Data_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains mappings for fields used to synchronize Photo Data between external service and Salesforce. Only fields specified in this mapping will be synched.</description>
    <label>Photo Data Field Mapping</label>
    <pluralLabel>Photo Data Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/fields/External_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Field_Name__c</fullName>
    <description>This field contains name of the field to map from external system</description>
    <label>External Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Specifies if the field should be synchronised</description>
    <inlineHelpText>Only fields mappings marked as &apos;Is Active&apos; will be synchronised</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Photo_Data_Field_Mapping__mdt/fields/Salesforce_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_Name__c</fullName>
    <description>This field contains name of the field to map in Salesforce</description>
    <inlineHelpText>Please put the API name here (with __c appendix)</inlineHelpText>
    <label>Salesforce Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CustomMetadataSelector.cls
/**
 * Class used for accessing Custom Metadata records
 */
public with sharing class CustomMetadataSelector {

    private static Photo_Data_Field_Mapping__mdt[] photoDataFieldMapping = null;

    /**
     * Returns all Photo Data Field Mappings records marked as active
     */
    public static Photo_Data_Field_Mapping__mdt[] getPhotoDataFieldMappingMetadata() {
        initPhotoDataFieldMappingMetadata();
        return photoDataFieldMapping;
    }

    private static void initPhotoDataFieldMappingMetadata() {
        if (photoDataFieldMapping == null) {
            photoDataFieldMapping = [
                SELECT Id, External_Field_Name__c, Salesforce_Field_Name__c 
                FROM Photo_Data_Field_Mapping__mdt 
                WHERE Is_Active__c = true
            ];
        }
    }
}